[book]
authors = ["Ankitects Pty Ltd and contributors"]
description = "Frequently asked questions about Anki. Anki is a program that makes learning easier."
language = "en"
multilingual = false
src = "src"
title = "Anki FAQs"

[build]
create-missing = true

[output.html]
no-section-label = true
git-repository-url = "https://github.com/ankitects/faqs/"
additional-css = ["css/misc.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
# sites that block programmatic access
exclude = [ 'quora\.com', 'reddit.com', 'superuser.com', 'github.com/open-spaced-repetition' ]

[output.html.redirect]
# redirect deleted pages to new pages to preserve legacy links
"./src/note-types-with-strange-names.md" = "./src/removing-duplicate-note-types.md"
